[package]
name = "xensieve-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
image = "0.24.9"
imageproc = "0.23.0"
inquire = {version = "0.7.0", features = ["date", "editor"]}
plotters = "0.3.5"
ratatui = "0.26.1"
xensieve = "0.3.0"


